### ISSUE TITLE
[BUG] scaling_plan_config seems required despite declared optional

### ISSUE THREAD

**Issue by mloskot** [claranet/terraform-azurerm-avd#1] opened 2024-01-15 18:09 UTC
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.6.5

### AzureRM Provider Version

3.82.0

### Affected Resource(s)/Data Source(s)

n/a

### Terraform Configuration Files

```hcl
module "avd" {
  source  = "claranet/avd/azurerm"
  version = "~> 7.2.0"

  client_name         = "mloskot"
  environment         = "test"
  location            = module.azure_region.location
  location_short      = module.azure_region.location_short
  resource_group_name = module.resource_group.resource_group_name
  stack               = "avd"

  logs_destinations_ids = [
    var.logs_storage_account_id # my SA in test environment
  ]
}
```

### Debug Output/Panic Output

```shell
│ Error: Error in function call
│
│   on .terraform/modules/avd/locals-avd.tf line 4, in locals:
│    4:   avd_service_principal_object_id = coalesce(var.scaling_plan_config.role_assignment.principal_id, one(data.azuread_service_principal.avd_service_principal[*].object_id))
│     ├────────────────
│     │ while calling coalesce(vals...)
│     │ data.azuread_service_principal.avd_service_principal is empty tuple
│     │ var.scaling_plan_config.role_assignment.principal_id is null
│
│ Call to function "coalesce" failed: no non-null, non-empty-string arguments.
```

### Expected Behaviour

Such a mininal module configuration as presented above to plan and apply with success, because `scaling_plan_config` is optional as per

https://github.com/claranet/terraform-azurerm-avd/blob/d1b974c99eae21021f85f4cbf96c4843c9281778/README.md?plain=1#L197

### Actual Behaviour

Terraform plan fails

### Steps to Reproduce

1. Create `main.tf` with the copy of the minimal configuration presented above 
2. `terraform init`
3. `terraform plan`

**Comment by zfiel** [comment] 2024-01-16 10:21
Hello @mloskot ,

Thank you for opening this issue. The issue is coming from the `coalesce` function. This will be fixed very soon.

**Comment by zfiel** [comment] 2024-01-22 07:19
Fixed in https://github.com/claranet/terraform-azurerm-avd/tree/v7.2.1
🚀

**Comment by mloskot** [comment] 2024-01-22 10:59
@zfiel Thank you! I will test it on my and as soon as the new version is available from https://registry.terraform.io/modules/claranet/avd/azurerm/7.2.1

**Comment by zfiel** [comment] 2024-01-22 13:20
@mloskot the new version is available, our apologies

**Comment by mloskot** [comment] 2024-01-22 15:13
@zfiel Thanks for publishing the new release. It looks like this issue has been fixed for me indeed. Thanks!

I think this issue as well as the following PR can be closed as completed
- #2

**Closed as completed** 2024-01-22 15:15 UTC
Labels: bug
